[package]
name = "gen-alg"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = "0.55.1"
rand = "0.9.1"
rayon = "1.10.0"
regex = "1.11.1"
roulette-wheel = "0.2.2"

[dev-dependencies]
rand = "0.9.1"
